# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Blazor WASM Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish files
      run: dotnet publish --no-restore --configuration Release --output output
    - name: Clone to gh-pages
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git checkout --orphan gh-pages
        git rm -rf .
        cp -r output/wwwroot/index.html output/wwwroot/404.html
        cp -r output/wwwroot/* .
        rm -r output
        touch .nojekyll
        git add .
        git commit -m "Auto commit by GitHub Pages"
        git push -f origin gh-pages
        
        
